--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cosmicnebula200/RockPaperScissors
build-by-default: true
branches:
- main
icon: "icon.png"
    path: ""
projects:
  RockPaperScissors:
    path: ""
...
